name: CI

on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Display macOS version
        run: sw_vers
      
      - name: Install Ansible
        run: brew install ansible
      
      - name: Install Ansible community.general collection
        run: ansible-galaxy collection install community.general
      
      - name: Syntax check
        run: ansible-playbook setup.yml --syntax-check
      
      - name: Run CI tests (dry-run)
        run: ansible-playbook setup.yml --tags ci_test -vv